channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - scipy
  - sympy
  - opencv
  - scikit-learn
  - scikit-image
  - networkx
  - bokeh
  - statsmodels
  - nbval
  - ipython
  - pandas
  - vdom
  - jupyterlab_launcher
  - watermark
  - nbgitpuller
  - biopython
